[package]
name = "sierra"
version = "0.1.0"
edition = "2018"


[dependencies]
cranelift = "0.74.0"
cranelift-jit = "0.74.0"
cranelift-module = "0.74.0"
mopa = "0.2.2"
tagged-box = { version = "0.1", features = ["56bits"] }
